### ISSUE TITLE
QQ音乐cookie Tab替换出错

### ISSUE THREAD

**Issue by YujiaCheng1996** [project-openwrt/luci-app-unblockneteasemusic#13]
设备是armv7架构Pandorabox。
使用QQ音乐并设置相应cookie后，启动失败。

报错信息是/usr/share/unblockneteasemusic/core/provider/qq.js中对应行替换不正确，'cookie':前应为Tab而实际替换成了字母t，导致没有认出t'cookie':。

应该是129行的\\\\t转义没有被正确理解：
sed -i -e "${qq_cookie_line}i \\\t'cookie': '${qq_cookie}'" "/usr/share/unblockneteasemusic/core/provider/qq.js"

望检查修复。

**Comment by 1715173329** [comment]
129行的代码为：
https://github.com/project-openwrt/luci-app-unblockneteasemusic/blob/3d77d5b15f130692b6568cff079d3c6e418c1b73/root/etc/init.d/unblockneteasemusic#L129
拥有三个反斜杠（不是两个），通过检查发布的release包，未发现拼写错误。
本人同样在使用QQ音源，并未发现任何问题。

**Comment by 1715173329** [comment]
此外，无法判断PandoraBox的busybox套件是否对sed做出了阉割，我仅保证本插件在 OpenWrt 18.06 上正常运作。

**Comment by YujiaCheng1996** [comment]
不是说源码写错了，就是我的设备理解这个转义有问题，日志提示：
/usr/share/unblockneteasemusic/core/provider/qq.js:8
t'cookie': 'uin=和谐'
 ^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/provider/match.js:6:6)

可能是被阉割了吧

可否考虑使用替换：
sed -i "s/'cookie':.*$/'cookie':\ ${qq_cookie}/" "/usr/share/unblockneteasemusic/core/provider/qq.js"
qq_cookie里的空格要转义

**Comment by 1715173329** [comment]
嘛。。特殊情况特殊对待。。
你可以根据你那边情况对init做出对应的修改以保证正常运作。。
