### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by PoiYuudachi** [project-openwrt/luci-app-unblockneteasemusic#14]
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

**Comment by 1715173329** [comment]
1. 请确保您的网络通畅
2. 请确保您的上游网关未开启劫持插件
3. 请手动访问 `music.163.com` 检查是否有证书错误
