### ISSUE TITLE
关于启动延时的建议

### ISSUE THREAD

**Issue by WROIATE** [project-openwrt/luci-app-unblockneteasemusic#26]
log：
```
{ Error: connect ENETUNREACH 59.111.181.38:443 - Local (0.0.0.0:0)
    at internalConnect (net.js:964:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
    at net.js:1062:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '59.111.181.38',
  port: 443 }

```
该情况发生在重启路由器时，而路由器启动以后手动重启插件即可正常使用，初步估计是启动时路由还在pppoe登录，无网络。若是该问题希望能够添加延迟启动选项

**Comment by 1715173329** [comment]
一般说来进程守护程序会在 5 分钟内自动重启程序，你可以尝试更改 init 中 START 的数值以查看效果。

**Comment by WROIATE** [comment]
> 一般说来进程守护程序会在 5 分钟内自动重启程序，你可以尝试更改 init 中 START 的数值以更改启动顺序。

试过了，不行，依然报错

**Comment by WROIATE** [comment]
我大概找到原因了？我在主文件里没有找到restart函数，只有start和stop。
还有就是strat函数里第一行的enable判断建议取消，这个判断会导致如果没在luci界面启动无法通过命令行使用start强制启动（我的openwrt有些情况下会抽风无法传递参数，只能用命令行）
